<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="1" failed="1" ignored="0" total="2" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="5737" started-at="2022-02-20T20:55:35 CET" finished-at="2022-02-20T20:55:41 CET">
    <groups>
    </groups>
    <test name="Default test" duration-ms="5737" started-at="2022-02-20T20:55:35 CET" finished-at="2022-02-20T20:55:41 CET">
      <class name="projectTests.ProfileTest">
        <test-method status="PASS" signature="Configuration()[pri:0, instance:projectTests.ProfileTest@8646db9]" name="Configuration" is-config="true" duration-ms="2375" started-at="2022-02-20T20:55:35 CET" finished-at="2022-02-20T20:55:38 CET">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Configuration -->
        <test-method status="FAIL" signature="editProfileTest()[pri:1, instance:projectTests.ProfileTest@8646db9]" name="editProfileTest" duration-ms="3117" started-at="2022-02-20T20:55:38 CET" finished-at="2022-02-20T20:55:41 CET">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[ [ERROR] Unexpected login message  expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError:  [ERROR] Unexpected login message  expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at projectTests.ProfileTest.editProfileTest(ProfileTest.java:22)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- editProfileTest -->
        <test-method status="FAIL" signature="screenshotOnFailureAndClose(org.testng.ITestResult)[pri:0, instance:projectTests.ProfileTest@8646db9]" name="screenshotOnFailureAndClose" is-config="true" duration-ms="199" started-at="2022-02-20T20:55:41 CET" finished-at="2022-02-20T20:55:41 CET">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=editProfileTest status=FAILURE method=ProfileTest.editProfileTest()[pri:1, instance:projectTests.ProfileTest@8646db9] output={null}]]]>
              </value>
            </param>
          </params>
          <exception class="java.io.IOException">
            <message>
              <![CDATA[Cannot create directory 'C:\Users\majad\Desktop\IT Bootcamp\projects\ITBootcampProjectFinal\screenshots'.]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.io.IOException: Cannot create directory 'C:\Users\majad\Desktop\IT Bootcamp\projects\ITBootcampProjectFinal\screenshots'.
at org.apache.commons.io.FileUtils.mkdirs(FileUtils.java:2200)
at org.apache.commons.io.FileUtils.createParentDirectories(FileUtils.java:1113)
at org.apache.commons.io.FileUtils.copyFile(FileUtils.java:843)
at org.apache.commons.io.FileUtils.copyFile(FileUtils.java:756)
at projectTests.BasicTest.screenshotOnFailureAndClose(BasicTest.java:95)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:62)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:385)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:321)
at org.testng.internal.TestInvoker.runConfigMethods(TestInvoker.java:700)
at org.testng.internal.TestInvoker.runAfterGroupsConfigurations(TestInvoker.java:676)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:660)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.io.IOException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- screenshotOnFailureAndClose -->
        <test-method status="SKIP" signature="Configuration()[pri:0, instance:projectTests.ProfileTest@8646db9]" name="Configuration" is-config="true" duration-ms="-1645386941624" started-at="2022-02-20T20:55:41 CET" finished-at="1970-01-01T01:00:00 CET">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Configuration -->
        <test-method status="SKIP" signature="changeProfileImage()[pri:2, instance:projectTests.ProfileTest@8646db9]" name="changeProfileImage" duration-ms="0" started-at="2022-02-20T20:55:41 CET" finished-at="2022-02-20T20:55:41 CET">
          <exception class="java.io.IOException">
            <message>
              <![CDATA[Cannot create directory 'C:\Users\majad\Desktop\IT Bootcamp\projects\ITBootcampProjectFinal\screenshots'.]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.io.IOException: Cannot create directory 'C:\Users\majad\Desktop\IT Bootcamp\projects\ITBootcampProjectFinal\screenshots'.
at org.apache.commons.io.FileUtils.mkdirs(FileUtils.java:2200)
at org.apache.commons.io.FileUtils.createParentDirectories(FileUtils.java:1113)
at org.apache.commons.io.FileUtils.copyFile(FileUtils.java:843)
at org.apache.commons.io.FileUtils.copyFile(FileUtils.java:756)
at projectTests.BasicTest.screenshotOnFailureAndClose(BasicTest.java:95)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:62)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:385)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:321)
at org.testng.internal.TestInvoker.runConfigMethods(TestInvoker.java:700)
at org.testng.internal.TestInvoker.runAfterGroupsConfigurations(TestInvoker.java:676)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:660)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.io.IOException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- changeProfileImage -->
        <test-method status="SKIP" signature="screenshotOnFailureAndClose(org.testng.ITestResult)[pri:0, instance:projectTests.ProfileTest@8646db9]" name="screenshotOnFailureAndClose" is-config="true" duration-ms="-1645386941630" started-at="2022-02-20T20:55:41 CET" finished-at="1970-01-01T01:00:00 CET">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- screenshotOnFailureAndClose -->
      </class> <!-- projectTests.ProfileTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
